---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-hyprland
# description will be included in the image's metadata
description: Hyprland image based off of Bazzite

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest

modules:
  - type: dnf
    repos:
      cleanup: true
      copr:
        - atim/starship # Starship
        - sdegler/hyprland # Hyprland
        - avengemedia/dms # DMS
      files:
        - vscodium.repo
    install:
      packages:
        # Sys Utils
        - btop
        - micro
        - cargo
        - clamav
        - clamav-update
        - clamd

        # CLI
        - kitty
        - zsh
        - fish
        - starship

        # Hyprland
        - hyprland
        - hyprcursor
        - hypridle
        - hyprlock
        - hyprpolkitagent
        - hyprtoolkit
        #- qt6ct-kde
        - hyprqt6engine
        - hyprland-qt-support
        - hyprland-guiutils

        # Shell
        - kvantum
        - dms
        
        # Games
        - gamescope

        # Dev
        - codium
        - typescript
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - lutris
        - ptyxis
        
  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - com.github.tchx84.Flatseal
      - notify: false
        scope: user
        install:
          # General
          - md.obsidian.Obsidian
          - com.vivaldi.Vivaldi
          - com.spotify.Client
          - com.discordapp.Discord
          # Games
          - com.heroicgameslauncher.hgl
          # System
          - com.github.Matoking.protontricks
  
  - type: files
    files:
      - source: system
        destination: /


  - type: signing # this sets up the proper policy & signing files for signed images to work fully
